version: '2'

services:

  resume-make:
    build:
      context: .
      dockerfile: ./.docker/resume.dockerfile
    command: make
    container_name: resume-make
    image: zblackwo/pandoc_resume:latest
    volumes:
      - .:/home/app/resume
