# This is a basic workflow to help you get started with Actions

name: build-resume

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    publish_resume:
      runs-on: ubuntu-latest
      name: Build and publish resume in html pdf docx and rtf
      steps:
        - uses: actions/checkout@v2
        - uses: rlespinasse/github-slug-action@v3.x
        - uses: docker://tdhopper/pandoc-context:latest
          with:
            args: >-
              -c make
        - name: rename html
          run: mv output/resume.html index.html
        - name: rename pdf
          run: mv output/resume.pdf zachary-blackwood-resume.pdf
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            branch: gh-pages
            message: 'Update resume html and pdf'

