# This is a basic workflow to help you get started with Actions

name: build-resume

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/mszep/pandoc_resume/resume_builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Test directory contents
        run: ls -al

      - name: Build resume
        run: make all

      - name: rename html
          run: mv output/resume.html index.html
      - name: rename pdf
          run: mv output/resume.pdf zachary-blackwood-resume.pdf

      - uses: EndBug/add-and-commit@v7
        with:
          add: "zachary-blackwood-resume.pdf index.html"
          branch: gh-pages
          message: 'Update resume html and pdf'

